# Generated by Django 2.0.4 on 2018-04-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20180421_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_link',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='url_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='resource',
            new_name='title',
        ),
    ]
